### ISSUE TITLE
Error extracting ROM where DTCM address is not 27E0000

### ISSUE THREAD

**Issue by LagoLunatic** [AetiasHax/ds-rom#3]
Tested on Castlevania: Portrait of Ruin:
```
>dsrom extract --rom ACBE00.nds --arm7-bios bios7.bin --path ./ACBE00 
[2024-09-09T19:34:57Z INFO  ds_rom::rom::rom] Saving ROM to path ./ACBE00
thread 'main' panicked at C:\dev\sre\tloz-nds\nds-io\lib\src\rom\rom.rs:353:47:
unknown autoload block
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Currently this library is coded to assume DTCM is always at 27E0000:
https://github.com/AetiasHax/ds-rom/blob/f7f2b300d9a0f9f568adb18674022e3b69fe43d0/lib/src/rom/raw/autoload_info.rs#L99

This game has it at 27C0000, so the program crashes on extract.

**Comment by AetiasHax** [comment]
It's fixed now in v0.2.2, thanks for reporting!
