### ISSUE TITLE
Panic when extracting Gyakuten Kenji 2

### ISSUE THREAD

**Issue by PhoenixBound** [AetiasHax/ds-rom#5]
When extracting the game Gyakuten Kenji 2 (BXOJ), the tool panics writing the arm9.bin out to the filesystem:

```
[2024-09-21T00:59:48Z INFO  ds_rom::rom::rom] Saving ROM to path ./gk2-extracted
[2024-09-21T00:59:48Z INFO  ds_rom::rom::rom] Decompressing ARM9 program
thread 'main' panicked at .\lib\src\rom\rom.rs:359:47:
unknown autoload block
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Since [this code](https://github.com/AetiasHax/ds-rom/blob/ef1a99cedba16818e358f104a1d1d0a96577f74f/lib/src/rom/rom.rs#L359) is related to separating ITCM and DTCM data from everything else, I'm guessing it's because of an extra entry at the end of the file that says "copy 0 bytes of data and 0 bytes of zeroes to $2400000":

![image](https://github.com/user-attachments/assets/b68b0937-839e-403f-921f-01bad32eb91b)

**Comment by AetiasHax** [comment]
2400000 is also the end of the main memory on the original DS so there couldn't possibly be anything there. Though as you pointed out, nothing is being copied there anyway. Very strange 🤔

It looks like `ds-rom` needs a way to store arbitrary autoload blocks somewhere, since it's hardcoded to only know about ITCM and DTCM right now.

**Comment by PhoenixBound** [comment]
Yeah I dunno... I think I read somewhere that debug models of the DS had more RAM, but that doesn't help much with guessing what its contents would be/why this autoload entry exists in a retail game.

The arbitrary autoload config thing would probably be a good futureproofing measure, if nothing else.

**Comment by AetiasHax** [comment]
This is fixed! Unknown autoloads can now be extracted and built (even if they are empty). I also noticed that the compressed code in Gyakuten Kenji 2 would not match the original ROM, so the I redesigned the compression algorithm. New release coming soon.
